version: '3'

services:
  neo:
    image: neo4j:latest
    environment:
      - "NEO4J_AUTH=neo4j/7BOHy2ASDt7&"
      - "NEO4J_dbms_memory_heap_max__size=4g"
      - "NEO4J_dbms_memory_pagecache_size=2g"
    ports:
      - "7474:7474"
      - "7687:7687"
    networks: 
      - backend
  webspoon:
    depends_on:
      - neo
    image: carl92/webspoon-neo4j:latest
    environment:
     - "JAVA_OPTS=-Xms4g -Xmx4g -DNEO4J_LOGGING_CONNECTION=Demo"
    ports:
      - "8080:8080"
    links:
      - neo
    networks: 
      - backend
networks:
  backend:
    driver: "bridge"

